### PR TITLE
Add fdroid flavor

### PR DESCRIPTION
**Pull request by p1gp1g**
This PR add flavors to Obtainium: `github` for the main and `fdroid`. The FDroid flavor change the packageId and does not add itself to the app list.

That way:
- FDroid build has a different packageId
- FDroid build does not track itself on github.

This PR is useful only if the reproducible build is impossible (see https://f-droid.org/2023/01/15/towards-a-reproducible-fdroid.html). With this PR we can start the FDroid inclusion process (if you agree of course) and if the reproducible build doesn't work, this is a fallback solution :)

---

To run and build the main flavor:

```
flutter run --flavor github
flutter build --flavor github
```

For FDroid:
```
flutter run --flavor fdroid -t lib/main_fdroid.dart
flutter build --flavor fdroid -t lib/main_fdroid.dart
```

---

Related issue: https://github.com/ImranR98/Obtainium/issues/30

---
Edit: Change flavor name

### CODE REVIEW

**Comment by ImranR98** [comment]
Hi, thanks for this PR. I'm not familiar with publishing on F-Droid but it [looks like](https://f-droid.org/docs/Submitting_to_F-Droid_Quick_Start_Guide/) we'd need to take some more steps to get that done. Would you be willing to set all that up as well? I've avoided the F-Droid issue so far as it doesn't seem worth the trouble to me, but we can go ahead with this if you're up for it.

**Comment by ImranR98** [comment]
Could you change the name of the non-Fdroid build from `no` to `main`

**Comment by p1gp1g** [comment]
Unfortunately, I can't, at least I have never found how to do it: gradle uses `main` under the hood already. It is still possible to use other names like `mainF` and `fdroidF`

**Comment by ImranR98** [comment]
Makes sense. How about `standard`?

**Comment by p1gp1g** [comment]
What do you prefer ? I am also thinking of `github` since it is the source intended to provide this build ?

**Comment by ImranR98** [comment]
Yes, `github` is good

**Comment by p1gp1g** [comment]
Done :)

**Comment by notahomosapien** [comment]
Hi,
Please consider reading [this article](https://privsec.dev/posts/android/f-droid-security-issues/) before publishing on F-Droid.

**Comment by p1gp1g** [comment]
> Hi, Please consider reading [this article](https://privsec.dev/posts/android/f-droid-security-issues/) before publishing on F-Droid.

1. Even if the app is published on f-droid, users don't have to install it from f-droid.
2. This blog post is very misleading. Most of the point from this blog post are outdated, others are also true for the playstore and/or the github releases or with an overestimated risk. Some points are still true.
3. This is not the right place to debate this :)

**Comment by notahomosapien** [comment]
> This blog post is very misleading. Most of the point from this blog post are outdated, others are also true for the playstore and/or the github releases or with an overestimated risk. Some points are still true.

Have you actually read It?, Its not outdated and Obtanium is not going to be published on Google Play, therefore the only point that also applied to Google Play (The trusted party problem) is also not applicable. Github releases is different story, but at least Developers upload APKs signed by themselves and not by some third-party.

> This is not the right place to debate this :)

Okay, Thanks for informing me; Let's end this conversation?

**Comment by linsui** [comment]
Any update?

**Comment by ImranR98** [comment]
> Any update?

Sorry for ignoring this for so long, I will look at it soon. Once this PR is merged, I don't remember what the process is to get it published on f-droid so will need to refresh my memory.

**Comment by linsui** [comment]
> I don't remember what the process is to get it published on f-droid so will need to refresh my memory.

No problem. Just ping me.

**Comment by ImranR98** [comment]
Merging to dev first so I can test it

**Comment by ImranR98** [comment]
Okay, the F-Droid flavour seems to build and run fine. Actually getting it up on F-Droid would be the next step.

**Pull request merged**
