### PR TITLE
Add Czech translation

### PR DESCRIPTION
**Pull request by zen0bit**
Initial version autotranslated

Correction will come soon...

### CODE REVIEW

**Comment by ImranR98** [comment]
Looks like there are a few JSON syntax issues. Also please add the language to the `supportedLocales` array in `main.dart`.

**Comment by zen0bit** [comment]
Check syntax pls.

If I still missed something...

**Comment by ImranR98** [comment]
Yes, looks like there are still errors. You can use a [JSON validator](https://duckduckgo.com/?t=ffab&q=json+validator&ia=answer) to help find them.

**Comment by zen0bit** [comment]
Validator said OK

**Pull request merged**
