### PR TITLE
Fix #397 Edit Category Colors & Accessible colors using HSLuv

### LINKED ISSUE #397: [Enhancement] Customized categories color
Looks like there's no way to changing the color of categories. Any chance to have this function?

### PR DESCRIPTION
**Pull request by djm2k**
Love the app, I have switched from F-Droid to using Obtainium for all my FOSS android apps.
I tried organising by category but I kept getting different shades of green.

This PR makes category colors more accessible using a combination of the [HSLuv (Pastel)](https://pub.dev/documentation/hsluv/latest/hsluv/Hsluv-class.html) color space and incrementing by the [Golden Angle](https://en.wikipedia.org/wiki/Golden_angle).

I removed the randomness as it was causing some duplicate colors with the golden angle.

### CODE REVIEW

**Comment by djm2k** [comment]
I was attempting to add a button on the settings page to re-generate a category's color similar to the minus button deleting them currently, to close #397.

I couldn't figure out how the categories/colours are stored so I just use the workaround of removing and re-adding the category.

**Comment by ImranR98** [comment]
> I couldn't figure out how the categories/colours are stored so I just use the workaround of removing and re-adding the category.

You can get `categories` from the `SettingsProvider`, and use `setCategories` to set them. The `categories` object is a `Map<String, int>` where the `String` is the category name and the `int` is the colour value.

**Comment by ImranR98** [comment]
Other than that, great PR! Didn't realize I had that function twice.

**Comment by djm2k** [comment]
Thanks for the tips, I managed to get it working!
Let me know of any issues, but I would love to see this released so I can switch off the debug app :)

**Comment by ImranR98** [comment]
Nice 👀
Will be merged as soon as the `numColorsGenerated` comment is addressed.

**Comment by djm2k** [comment]
@ImranR98 is that what you were after? Feel free to leave review comments for anything else
Thanks again!

**Comment by ImranR98** [comment]
@djm2k no, there was nothing wrong with the link comment, I was talking about repeating colours. You should be able to see the review comments I left on the "Files Changed" tab: 
image

**Comment by djm2k** [comment]
Thanks for the screenshot, I think those "pending" comments don't come through until you submit the review or something similar. I will add in your snippet now :)

**Comment by djm2k** [comment]
@ImranR98 Should be good to go! let me know if there's anything else

**Comment by ImranR98** [comment]
Whoops, you're right - I didn't actually submit the review comments. Looks good.

**Pull request merged**
