### PR TITLE
Add "Community App Sources" translation and button to Add App Screen

### LINKED ISSUE #1727: Move Obtainium Apps to Add App Screen
**Describe the feature**
I did not know that the [obtainiun suggested apps](https://github.com/ImranR98/apps.obtainium.imranr.dev?tab=readme-ov-file) screen even existed until after months of using obtainium. It is hidden away at the bottom of the setting screen after tapping the 4 squares icon.
Screenshot_1

I propose that this screen be moved to the top of the "Add App" section under a "Community App Sources" button. This will make this feature known and not hidden away in settings. It will also make Obtainiun more user friendly so people can install apps from source without needing to understand how GitHub releases work.
screenshot_2

### PR DESCRIPTION
**Pull request by Erengun**
**Resolves #1727**

This pull request introduces a new button labeled **"Community App Sources"** to the **AddAppPage**. When clicked, this button will open an external application with the URL: [https://apps.obtainium.imranr.dev/](https://apps.obtainium.imranr.dev/). Translations for the "Community App Sources" label have been included for multiple languages to ensure international support.

### Changes in this PR:
- Added a **"Community App Sources"** button on the **AddAppPage**
- Integrated translations for the button text across various languages
- Launched an external URL when the button is clicked

### Screenshots:

<details>
  <summary>Dark Mode</summary>
  
  Screenshot_dark
  
</details>

<details>
  <summary>Light Mode</summary>
  
  Screenshot_light
  
</details>

### CODE REVIEW

**Comment by ImranR98** [comment]
We already have a link to this on the settings page. I agree with putting it on the add app page too, but this button is too prominent. Maybe we could have it on the bottom rigth, styled similarly to the "Supported Sources" link. Shortened to something like "Crowdsourced Configs", it should fit on one line on most screens.

**Comment by Erengun** [comment]
Hey @ImranR98 , thanks for the feedback! As you suggested, I’ve moved the button to the **bottom right** and styled it similarly to the "Supported Sources" link. I’ve also shortened the text to **"Crowdsourced App Configs"**, so it fits on one line on most screens.

To give you options, I’ve placed the button:
- **In a row at the bottom right** (similar to "Supported Sources")
- **In a column**, both with **left alignment** and **center alignment** for comparison.

Take a look at the screenshots below and let me know which placement you think works best:

<details>
  <summary>Row aligned (Bottom Right)</summary>
  
  Screenshot_row_aligned

</details>

<details>
  <summary>Column Left aligned</summary>
  
  Screenshot_column_left_aligned

</details>

<details>
  <summary>Column Center aligned</summary>
  
  Screenshot_column_center_aligned

</details>

**Comment by ImranR98** [comment]
Thanks. Row aligned (bottom right) looks good.

**Comment by Erengun** [comment]
Then its committed and Ready for review. @ImranR98

**Pull request merged**
