### PR TITLE
Update zh.json

### PR DESCRIPTION
**Pull request by ArcticFoxPro**
## Dear Obtainium Author

~~Please hold off on merging this PR, I need to discuss the appropriateness of the Simplified Chinese translation with @LilligantMatsuri .~~

The discussion on Chinese translation has been completed and PR can be merged.

## PR 说明（Simplified Chinese）

- `showWebInAppView`：“应用详情页显示来源网页”可能会被理解为显示网址字符串，“应用详情页显示来源网页内容”强调了显示的是网页内容 WebView 而非网址。
- `appsNotUpdated`、`xAndNMoreUpdatesFailed`：在一个软件内，“应用”和“应用程序”术语似乎可以统一掉。
- `releaseAsset`：原因详见 #1562 。
- `categoryDeleteWarning`：“被删除类别下的应用将恢复为未分类状态”改为“被删除类别的应用将恢复为未分类状态”。在删除类别这个操作下，类别是 Obtainium 跟踪的应用的一个属性，似乎“类别下的应用”表达了奇怪的主从关系，不是很妥当。
- `shizukuOldAndroidWithADB`：“请更新 Android 系统版本”强调了更新的对象是 Android 系统，避免被误认为更新 Android 软件。
- `shizukuPretendToBeGooglePlay`：与 `beforeNewInstallsShareToAppVerifier` 统一翻译格式：动作在前，条件在后。
- `wiki`：似乎在简体中文互联网环境下，“维基”特指了维基基金会及其关联产品，“Wiki”泛指说明文档。比如手游《明日方舟》的同人文档被称为 PRTS Wiki 而非 PRTS 维基，米哈游米游社的观测枢·Wiki 也是如此。
- `tooManyRequestsTryAgainInMinutes`：“请”可明确操作主体是用户。
- `bgUpdateGotErrorRetryInMinutes`：“预定”是与日程相关的正式用语，这里用“将”即可传达同样信息。
- `xAndNMoreUpdatesFailed`：统一翻译。

- `trackOnlyInBrackets`、`searchableInBrackets`：更正半角标点为全角。
- `enableBackgroundUpdates`：改为“启用全局后台更新”突出全局性。
- `exemptFromBackgroundUpdates`：“仅此应用生效，即使已启用全局后台更新”更明确了选项条件。
- `highlightTouchTargets`: “触摸”只表达了触碰对象，并不特指和对象发生交互。
- `shizukuPretendToBeGooglePlay`：Google Play 不是确定的字符串，在这里指代了 Play Store 实体，无需双引号。
- `useLatestAssetDateAsReleaseDate`：英文 Latest 通常在简体中文对应“最新”而非“最近”。

- `useMaterialYou`: 原因详见 https://github.com/ImranR98/Obtainium/pull/1608#issuecomment-2095730863 .

## PR Notes (English)

- `showWebInAppView`: The phrase "应用详情页显示来源网页" might be interpreted as displaying the URL string, whereas "应用详情页显示来源网页内容" emphasizes that it is the content of the web page (WebView) rather than the URL that is shown.
- `appsNotUpdated`, `xAndNMoreUpdatesFailed`: Within the context of a software application, the terms "应用" and "应用程序" seem interchangeable and could be unified for consistency.
- `releaseAsset`: Refer to issue #1562 for the rationale behind this change.
- `categoryDeleteWarning`: "被删除类别下的应用将恢复为未分类状态" amended to "被删除类别的应用将恢复为未分类状态" clarifying that applications assigned to the deleted category will become uncategorized. The previous phrasing suggested an unusual hierarchy between categories and apps.
- `shizukuOldAndroidWithADB`: Saying "请更新 Android 系统版本" emphasizes that the update is for the Android system itself, avoiding confusion that it might refer to updating an Android app.
- `shizukuPretendToBeGooglePlay`: Aligns translation format with `beforeNewInstallsShareToAppVerifier` for consistency, placing the action before the condition.
- `wiki`: In the Simplified Chinese online landscape, "维基" typically refers specifically to projects affiliated with the Wikimedia Foundation, whereas "Wiki" is a more general term for documentation. For instance, the fan-fiction archive for the game Arknights is named PRTS Wiki, not PRTS 维基, reflecting this distinction.
- `tooManyRequestsTryAgainInMinutes`: Adding "请" clarifies that the user is the one who should perform the action.
- `bgUpdateGotErrorRetryInMinutes`: The word "预定" is formal and associated with scheduling; using "将" instead effectively communicates the intended message without the added formality.
- `xAndNMoreUpdatesFailed`: Standardizes the translation for consistency.

- `trackOnlyInBrackets`, `searchableInBrackets`: Convert half-width punctuation to full-width.
- `enableBackgroundUpdates`: Change to "Enable global background updates" to emphasize the global nature.
- `exemptFromBackgroundUpdates`: “仅此应用生效，即使已启用全局后台更新” clarifies the condition of the option.
- `highlightTouchTargets`: In Chinese, "触摸" refers to touching an object, not specifically interacting with it.
- `shizukuPretendToBeGooglePlay`: Google Play is not a literal string here, it represents the Play Store entity, so no need for double quotes.
- `useLatestAssetDateAsReleaseDate`: In English, "Latest" typically corresponds to "newest"（最新） rather than "most recent"（最近） in Simplified Chinese.

- `useMaterialYou`: Refer to https://github.com/ImranR98/Obtainium/pull/1608#issuecomment-2095730863 for the rationale behind this change.

### CODE REVIEW

**Comment by LilligantMatsuri** [comment]
@ArcticFoxPro 工作时间，我就简略回复了，见谅。

> `showWebInAppView`：“应用详情页显示来源网页”可能会被理解为显示网址字符串，“应用详情页显示来源网页内容”强调了显示的是网页内容 WebView 而非网址。

可以，很严谨。

> `appsNotUpdated`、`xAndNMoreUpdatesFailed`：在一个软件内，“应用”和“应用程序”术语似乎可以统一掉。

我漏翻的新字符串。机翻的结果通常是“应用程序”，我之前统一用的是“应用”。

> `categoryDeleteWarning`：“被删除类别下的应用将恢复为未分类状态”改为“被删除类别的应用将恢复为未分类状态”。在删除类别这个操作下，类别是 Obtainium 跟踪的应用的一个属性，似乎“类别下的应用”表达了奇怪的主从关系，不是很妥当。
> `shizukuOldAndroidWithADB`：“请更新 Android 系统版本”强调了更新的对象是 Android 系统，避免被误认为更新 Android 软件。
> `shizukuPretendToBeGooglePlay`：与 beforeNewInstallsShareToAppVerifier 统一翻译格式：动作在前，条件在后。

同意。

> `wiki`：似乎在简体中文互联网环境下，“维基”特指了维基基金会及其关联产品，“Wiki”泛指说明文档。比如手游《明日方舟》的同人文档被称为 PRTS Wiki 而非 PRTS 维基，米哈游米游社的观测枢·Wiki 也是如此。

同样是我遗漏了。如果是我的话，也会改为“Wiki”。

> `tooManyRequestsTryAgainInMinutes`：“请”可明确操作主体是用户。
> `bgUpdateGotErrorRetryInMinutes`：“预定”是与日程相关的正式用语，这里用“将”即可传达同样信息。

同意。

> `xAndNMoreUpdatesFailed`：统一翻译。

我本地也已经改了，还没提 PR。（除此之外还有几条）

**结论：没有异议。(I have no problem with this PR.)**

**Comment by ArcticFoxPro** [comment]
@LilligantMatsuri 
根据 Google Material 博客的这篇文章：https://material.io/blog/start-building-with-material-you ，似乎可以看出 Material You 术语已经包含了 Dynamic color 动态颜色，Material You = Material Design 3 + Dynamic color。依据是作者在前面描述 Material You 对象术语时描述了子属性 Dynamic color，后面描述 Material’s new color system 和 Material Theme Builder 时又将对象术语换回了 Material Design 3。

因此，
```
"useMaterialYou": "使用 Material You 配色",
```
是否可以去掉“配色”二字？Obtainium 英文原文是
```
"useMaterialYou": "Use Material You",
```

**Comment by LilligantMatsuri** [comment]
@ArcticFoxPro 这几点我都没有意见，您的严谨令我敬佩。只对第一条做一点说明：
> `trackOnlyInBrackets`、`searchableInBrackets`：更正半角标点为全角

这两处半角括号是我特意保留的，因为这部分文字曾经是斜体，用全角括号不是很美观（字符间距）。不过现在已经改为正体了，使用全角也是应该的。

另外，今后发现有不妥的地方直接修改就好，无需征求我的意见。我修订译文的频率不高，通常会等改动积累较多以后再提交，所以有些错误不会及时更正。也正因如此，我有时会忘记或忽视一些字符串，所以错漏不少，请大佬多斧正了🙏

**Comment by ArcticFoxPro** [comment]
> @ArcticFoxPro 这几点我都没有意见，您的严谨令我敬佩。只对第一条做一点说明：
> > `trackOnlyInBrackets`、`searchableInBrackets`：更正半角标点为全角
> 
> 这两处半角括号是我特意保留的，因为这部分文字曾经是斜体，用全角括号不是很美观（字符间距）。不过现在已经改为正体了，使用全角也是应该的。
> 
> 另外，今后发现有不妥的地方直接修改就好，无需征求我的意见（如果有疑问我会回复）。我修订译文的频率不高，通常会等改动积累较多以后再提交，所以有些错误不会及时更正。也正因如此，我有时会忘记或忽视一些字符串，所以错漏不少，请大佬多斧正了🙏

我不是大佬🙏，我对 Obtainium 软件功能的理解远远不够，况且我上次还有因为不了解正则表达式捕获组术语导致的翻译问题。

**Pull request merged**
