### PR TITLE
[discussion] Rework Gitlab .apk retrieval strategies

### PR DESCRIPTION
**Pull request by akramer-zibra**
`Obtainium 1.0.3` has two strategies to retrieve .apk information from Gitlab: This is either (a) by using the `Gitlab API` with a Private Access Token (PAT) or either (b) by using the `tags`-page of a repository. In some cases (e.g. Aurora Store) the `tags`-page does not have information about related .apk files, but the `Gitlab API` has (#1381, #1380, #697).

This patch will rework the strategy composition (a, b) and provide an interface to add other retrieval strategies, for example (c) scraping the `releases`-page of a repository. 

So the goal of this patch is to retrieve consistent .apk information with every retrieval strategy (API, tags-page, etc.) and in its consequence to make the `Gitlab API Token` superfluous in case of public repositories. Not every Obtainium user might have a Gitlab account to create a Private Access Token (PAT).

### CODE REVIEW

**Comment by akramer-zibra** [comment]
This patch comes also with the suggestion to refactor the .apk retrieval code into separate RetrievalStrategy classes and so decrease function complexity

**Comment by akramer-zibra** [comment]
Hey @ImranR98 , is there a special reason Obtainium scrapes `tags`-page instead of `releases`-page in case of Gitlab repositories? The releases-pages may provide more relevant information as the tags-pages do 🤔

**Comment by akramer-zibra** [comment]
> Hey, appreciate the effort

Oh, hey. And I appreciate your work and love for this project! Obtainium fills an essential part in my smartphone setup. This is why it would be a pleasure to give something back.

> What change is this referring to? From what I can see, you haven't modified either retrieval strategy - I only see that the existing code from GitLab.getLatestAPKDetails have been put into their own separate classes.

Yes. You are right. I did some reverse engineering to understand this code and have not yet added anything 😅. 

> I don't agree with the separation of GitLab specific code into a separate class outside of the GitLab class. Especially given that this new class has only one function (retrieve) and given that it needs you to pass an instance of GitLab into it anyways.

This is a common Design Pattern called `Strategy` (https://refactoring.guru/design-patterns/strategy), which is used to encapsulate "interchangeable algorithms" and so prevent functions from bloating. Sure, you are right. It seems a bit odd to give each `Strategy`-class a reference to the `Gitlab` instance, but this is due to the fact that `sourceRequest(...)` is generically defined within the `AppSource`-class and therefore is not accessible without a reference. Some further refactoring could resolve this, but I think this would go too far at this point.

> All pages have content that is loaded in with JavaScript and cannot therefore be scraped. 

You are absolutely right. I haven't seen this on my first glance. My bad! But nevertheless the JavaScript code e.g. on the `releases`-page uses Gitlab's public `GraphQL API` to retrieve the release information of a project. This API endpoint (https://gitlab.com/api/graphql) is public as well as Gitlab's `REST API`.

> We don't scrape the tags page, we download an RSS feed XML file from the tags page, then extract info from it (in fact it contains some info from the releases page including APK links).

Now I understand why Obtainium uses the RSS feed of the `tags`-page, but I do not understand why Obtainium uses the `REST API` only if a `Private Access Token` (PAT) is configured? The `REST API` does not need a `Private Access Token` to retrieve public data from public repositories. The Access Token is mandatory for private repositories etc. but not for public data 🤔. 

```dart
String? PAT = await getPATIfAny(hostChanged ? additionalSettings : {});

if (PAT != null) {
    GitlabRestApiStrategy apiStrategy = GitlabRestApiStrategy(this, standardUrl, additionalSettings);
    apkDetailsList = await apiStrategy.retrieve();
} else {
    GitlabTagsPageStrategy tagsPageStrategy = GitlabTagsPageStrategy(this, standardUrl, additionalSettings);
    apkDetailsList = await tagsPageStrategy.retrieve();
}
```

We already discussed in other comments that the `tags`-page and its RSS feed lack in some cases relevant .apk URLs (e.g. AuroraStore).

I do not see any reason why to use any other retrieval strategy than the official APIs, because both APIs will provide every public data available. A `Private Acces Token` is mandatory to access private repositories. Scraping other endpoints or pages or feeds does not lever this out.

For this reason, I see at least one option to improve the retrieval code:

Use either Gitlab's `REST API` or `GraphQL API` with an optional injection of the `Private Access Token` to access private data. 

What do you think @ImranR98 ?

**Comment by ImranR98** [comment]
You're right - I remember thinking the API required a key even for public repos, not sure where I got that idea but it's not the case. Using the GraphQL API was also a great idea as a fallback but I guess it's not needed since the regular API does work w/o auth.

So we can just get rid of all tags RSS related code (remove the if-else) and only include the `?private_token=` query param if a token is defined.

**Comment by ImranR98** [comment]
Also thanks for the link to https://refactoring.guru/design-patterns/strategy, seems interesting but probably not applicable here (I think the `AppSource` class as a whole could be considered as kind of like a Strategy class).

**Comment by ImranR98** [comment]
Just checking - do you plan on updating this PR or should I go ahead and make the change?

**Comment by akramer-zibra** [comment]
> Just checking - do you plan on updating this PR or should I go ahead and make the change?

Hey @ImranR98 . I can't get round to working on the code right now, so I am happy if you can implement what we found out 😀

**Comment by akramer-zibra** [comment]
Hey @ImranR98 . I found some time to make the changes we discussion above. Therefore I created a new PR (#1459) and so close this one. As we also discussed above the refactorings in this approach seem out of scope.

**Pull request closed without merging**
